[sambashare]
   path = /sambashare
   browseable = yes
   read only = no
   guest ok = no
   valid users = bridge
   create mask = 0664
   directory mask = 0775
   force user = bridge
   force group = bridge
   strict allocate = yes
   allocation roundup size = 1048576
   min receivefile size = 16384
   write cache size = 1048576
   socket options = TCP_NODELAY IPTOS_LOWDELAY
   aio write size = 1
   aio read size = 1
